# Generated by Django 5.1.2 on 2024-10-14 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_quiz_time_limit_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskresult',
            name='fill_in_the_blank_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.fillintheblanktask'),
        ),
        migrations.AlterField(
            model_name='usertaskresult',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.task'),
        ),
    ]
